version: "3.3"
services:
  api-docs:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./api.json:/api.json
    environment:
      SWAGGER_JSON: /api.json
  reference-api:
    build: .
    user: node
    environment:
      - NODE_ENV=production
      - PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - ./tests:/home/node/app/tests
    command: "npm start"
